#!/bin/sh

if [ "$(uname)" = Darwin ]; then
    defaults write -g AppleAccentColor -integer 5
    defaults write -g AppleAntiAliasingThreshold -integer 4
    defaults write -g AppleAquaColorVariant -integer 1
    defaults write -g AppleEnableSwipeNavigateWithScrolls -boolean false
    defaults write -g AppleHighlightColor -string '0.968627 0.831373 1.000000 Purple'
    defaults write -g AppleICUForce24HourTime -boolean true
    defaults write -g AppleInterfaceStyle -string Dark
    defaults write -g AppleInterfaceStyleSwitchesAutomatically -boolean true
    defaults write -g AppleKeyboardUIMode -integer 0
    defaults write -g AppleLocale -string en_US
    defaults write -g AppleMiniaturizeOnDoubleClick -boolean false
    defaults write -g AppleReduceDesktopTinting -boolean true
    defaults write -g AppleShowAllExtensions -boolean true
    defaults write -g AppleShowScrollBars -string Automatic
    defaults write -g CGDisableCursorLocationMagnification -boolean true
    defaults write -g InitialKeyRepeat -integer 25
    defaults write -g KB_DoubleQuoteOption -string '“abc”'
    defaults write -g KB_SingleQuoteOption -string '‘abc’'
    defaults write -g KeyRepeat -integer 2
    defaults write -g NSAutomaticCapitalizationEnabled -boolean false
    defaults write -g NSAutomaticDashSubstitutionEnabled -boolean false
    defaults write -g NSAutomaticPeriodSubstitutionEnabled -boolean false
    defaults write -g NSAutomaticQuoteSubstitutionEnabled -boolean false
    defaults write -g NSAutomaticSpellingCorrectionEnabled -boolean false
    defaults write -g NSAutomaticTextCompletionEnabled -boolean true
    defaults write -g com.apple.keyboard.fnState -boolean true
    defaults write -g com.apple.mouse.scaling -string -1
    defaults write -g com.apple.sound.beep.feedback -integer 0
    defaults write -g com.apple.sound.beep.flash -integer 0
    defaults write -g com.apple.sound.beep.volume -float 0.0
    defaults write -g com.apple.sound.uiaudio.enabled -integer 0
    defaults write -g com.apple.springing.delay -float 0.5
    defaults write -g com.apple.springing.enabled -boolean true
    defaults write -g com.apple.swipescrolldirection -boolean false
    defaults write -g com.apple.trackpad.forceClick -boolean false
    defaults write -g com.apple.trackpad.scaling -float 0.6875

    defaults write com.apple.universalaccess classicInvertColor -boolean false
    defaults write com.apple.universalaccess closeViewDesiredZoomFactor -float 1.8971893120623624
    defaults write com.apple.universalaccess closeViewHotkeysEnabled -boolean false
    defaults write com.apple.universalaccess closeViewPanningMode -integer 0
    defaults write com.apple.universalaccess closeViewScrollWheelToggle -boolean true
    defaults write com.apple.universalaccess closeViewSmoothImages -boolean false
    defaults write com.apple.universalaccess closeViewSplitScreenRatio -float 0.20000000000000001
    defaults write com.apple.universalaccess closeViewZoomDisplayID -integer 0
    defaults write com.apple.universalaccess closeViewZoomFactor -float 1
    defaults write com.apple.universalaccess closeViewZoomFactorBeforeTermination -float 1
    defaults write com.apple.universalaccess closeViewZoomedIn -boolean false
    defaults write com.apple.universalaccess contrast -float 0.0
    defaults write com.apple.universalaccess differentiateWithoutColor -boolean false
    defaults write com.apple.universalaccess dwellHideUITimeout -float 15
    defaults write com.apple.universalaccess grayscale -boolean false
    defaults write com.apple.universalaccess grayscaleMigrated -boolean true
    defaults write com.apple.universalaccess hoverTextEnabled -boolean false
    defaults write com.apple.universalaccess hudNotifiedConstrast -float 0.0
    defaults write com.apple.universalaccess increaseContrast -boolean false
    defaults write com.apple.universalaccess keyboardAccessEnabled -boolean false
    defaults write com.apple.universalaccess keyboardAccessFocusRingTimeout -float 15
    defaults write com.apple.universalaccess keyboardAccessPassthroughMode -boolean false
    defaults write com.apple.universalaccess mouseDriverCursorSize -float 1.7210101082004556
    defaults write com.apple.universalaccess reduceMotion -boolean false
    defaults write com.apple.universalaccess reduceTransparency -boolean false
    defaults write com.apple.universalaccess restoreTrueToneEnabled -boolean false
    defaults write com.apple.universalaccess selectedTab -integer 14
    defaults write com.apple.universalaccess sessionChange -boolean false
    defaults write com.apple.universalaccess showToolbarButtonShapes -boolean false
    defaults write com.apple.universalaccess showWindowTitlebarIcons -boolean true
    defaults write com.apple.universalaccess slowKey -boolean false
    defaults write com.apple.universalaccess slowKeyDelay -integer 250
    defaults write com.apple.universalaccess stickyKey -boolean false
    defaults write com.apple.universalaccess switchAutoScanElementInterval -float 0.5
    defaults write com.apple.universalaccess switchAutoScanPanelInterval -float 0.5
    defaults write com.apple.universalaccess switchCoalescePressesDuration -float 0.0
    defaults write com.apple.universalaccess switchFirstElementDelay -float 0.0
    defaults write com.apple.universalaccess switchHideUITimeout -float 15
    defaults write com.apple.universalaccess switchHoldBeforeRepeatDuration -float 3
    defaults write com.apple.universalaccess switchMinimumPressDuration -float 0.0
    defaults write com.apple.universalaccess switchSweepingCursorSpeed -float 5
    defaults write com.apple.universalaccess useStickyKeysShortcutKeys -boolean false
    defaults write com.apple.universalaccess whiteOnBlack -boolean false
fi
