#!/usr/bin/env sh
set -e
set -u

mkdir -p ~/Library/Logs/
exec >>~/Library/Logs/local.strager.back-up.log 2>&1

cd "$(dirname "${0}")/../../.."
PATH="${HOME}/.nix-profile/bin:${PATH}"
# HACK(strager): Ignore archive errors for now.
exit_status=0
python3 -m stragerbackup.archive || exit_status="${?}"
# Replicate even if there were errors archiving. "operation not permitted" is a
# common error due to Apple privacy jails.
python3 -m stragerbackup.replicate
exit "${exit_status}"
