#!/usr/bin/env zsh

setopt err_exit
setopt pipe_fail
setopt unset

autoload colors

here="$(cd "$(dirname "${0}")" && pwd)"

generate_strager_initialize_ls_colors() {
    colors

    # TODO(strager): Also use these colors for GNU coreutils' ls and for macOS'
    # ls.
    local ls_colors=(
        "no=${color[none]}"  # Regular file

        "bd=${color[yellow]}"  # Block device
        "cd=${color[yellow]}"  # Character device
        "di=${color[blue]}"  # Directory
        "ex=${color[red]}"  # Executable
        "ln=${color[magenta]}"  # Symlink
        "pi=${color[yellow]}"  # FIFO
        "so=${color[green]}"  # Socket
    )

    printf '# WARNING: This file was generated by %s.\n' "$(basename "${ZSH_ARGZERO}")"
    printf '\n'
    printf '# Configure the list-colors zstyle.\n'
    printf '# This function is generated to avoid the start-up overhead and\n'
    printf '# pollution of the *colors* function.\n'
    printf 'strager_initialize_ls_colors() {\n'
    printf '    zstyle ":completion:*:default" list-colors'
    printf ' %q' "${ls_colors[@]}"
    printf '\n'
    printf '}\n'
}

generate_strager_initialize_ls_colors >"${here}/strager/strager_initialize_ls_colors"
