fpath=(~/.zsh/strager "${fpath[@]}")

# Environment.
export EDITOR=emacsclient
export PATH="${HOME}/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/go/bin:${PATH}"
if [[ "${HOST}" = strammer ]]; then
  export PATH="/Users/strager/tmp/Projects/nvm/versions/node/v18.6.0/bin:${PATH}"
  export PATH="/opt/homebrew/Cellar/watchman/2023.03.27.00/bin:${PATH}"
fi

if [[ -o interactive ]]; then
    # strager_initialize_post_prompt calls strager_initialize_nix.
    :
else
    strager_initialize_nix
fi

# Tell glibc in Nix-installed programs where to find locales.
for file in /usr/lib/locale/locale-archive; do
  if [ -f "${file}" ]; then
    export LOCALE_ARCHIVE="${file}"
    break
  fi
done

# Configure other programs.
export FZF_DEFAULT_COMMAND="$(cat ~/.config/fzf/FZF_DEFAULT_COMMAND)"
export FZF_DEFAULT_OPTS='--info=hidden --no-mouse'
