# Saved history.
HISTFILE=~/.zshhistory
HISTSIZE=100000
SAVEHIST=100000
setopt hist_find_no_dups
setopt inc_append_history
unsetopt hist_ignore_space

# Command interpretation.
setopt autocd
setopt chase_dots
setopt interactive_comments

# Keyboard bindings.
bindkey -e

# TODO(strager): select-word-style bash (except for ^W).

bindkey "${terminfo[kdch1]}" delete-char

autoload -U up-line-or-beginning-search
zle -N up-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up

autoload -U down-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search # down

autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# Completion.
autoload -Uz compinit
compinit

# Environment.
export EDITOR=vim
export PATH="${HOME}/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}"
if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# The prompt:
#
#     ~/Applications> false
#     ~/Applications 1> cd /tmp
#     /tmp>
setopt prompt_subst
PROMPT=
# Current directory.
PROMPT="${PROMPT}%F{green}\$(prompt_cwd)%f"
prompt_cwd() {
    prompt_shrink_path "$(print -P %~)"
}
# Replace /foo/bar/baz with /f/b/baz.
prompt_shrink_path() {
    local path="${1}"
    printf %s "${path//(#b)([^\/])[^\/]#\//${match[1]}/}"
}
# Exit code of previous command.
PROMPT="${PROMPT}%(0?;; %F{red}%?%f)"
# Terminator.
PROMPT="${PROMPT}> "

# iTerm 2 integration.
source ~/.zsh/../vendor/iterm2-website/source/shell_integration/zsh

# Make ls print colours by default.
ls() {
    /bin/ls -G "${@}"
}

# Git aliases.
gs() {
    git status -s -b "${@}"
}
gc() {
    git commit -v "${@}"
}
g.() {
    git add -p "${@}"
}
gd() {
    git diff "${@}"
}
gp() {
    git checkout -p "${@}"
}
gr() {
    git rebase "${@}"
}
grc() {
    git rebase --continue "${@}"
}
gar() {
    git add --all .
}
ga() {
    git commit --amend --reuse-message=HEAD
}

# Input styling.
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
typeset -A ZSH_HIGHLIGHT_STYLES
# TODO(strager): Fix the following issues:
# * https://github.com/zsh-users/zsh-syntax-highlighting/issues/277
# * https://github.com/zsh-users/zsh-syntax-highlighting/issues/239
# * https://github.com/zsh-users/zsh-syntax-highlighting/issues/202
# TODO(strager): Underline /absolute/path commands but not
# $PATH commands.
_command_style='fg=26'
_argument_style='fg=39'
ZSH_HIGHLIGHT_STYLES[alias]="${_command_style}"
ZSH_HIGHLIGHT_STYLES[arg0]="${_command_style}"
ZSH_HIGHLIGHT_STYLES[builtin]="${_command_style}"
ZSH_HIGHLIGHT_STYLES[command]="${_command_style},underline"
ZSH_HIGHLIGHT_STYLES[comment]='fg=red'
ZSH_HIGHLIGHT_STYLES[default]="${_argument_style}"
ZSH_HIGHLIGHT_STYLES[double-hypen-option]="${_argument_style}"
ZSH_HIGHLIGHT_STYLES[function]="${_command_style}"
ZSH_HIGHLIGHT_STYLES[hashed-command]="${_command_style},underline"
ZSH_HIGHLIGHT_STYLES[path]="${_argument_style},underline"
ZSH_HIGHLIGHT_STYLES[precommand]="${_command_style}"
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=093'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="${_argument_style}"
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Configure other programs.
export FZF_DEFAULT_OPTS='--no-progress --inline-info'
